version: '3'
services:
  redis:
    image: redis:alpine
  mongodb:
    image: mongo
  service:
    build: .
    command: ruby app.rb
    environment:
      - WEB_SERVER_PORT=4444
      - MONGO_HOST=mongodb:27017
      - MONGO_TIMEOUT=3
      - REDIS_HOST=redis://redis:6379/15
      - REDIS_TIMEOUT=3
      - WAIT=2
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4444:4444"
